Feat/template and acts
Rzyfront/Bait-App pull request #222
Opened 2023-05-02 19:26 UTC by Diana0617

Cambie lo que decia legal en la parte de tratamiento de datos, quedo solo el manejo. 

Coloque al dar click en el boton de inscribir el local en el footer, fuera al formulario grande de una vez. 

Al dar click en el logo de instagram va a una nueva pagina.

2023-05-02 20:07 UTC, juancamilo1478 requested changes
el codigo  esta tocando el mapa con cosas viejas

2023-05-03 01:18 UTC, DianaQuintanaY submitted a review, later dismissed

2023-05-03 23:08 UTC, Rzyfront submitted a review, later dismissed

2023-05-03 23:48 UTC, DianaQuintanaY submitted a review, later dismissed

2023-05-04 16:46 UTC, closed without merging